services:
  dicomlistener:
    image: darthunix/dcmtk:latest
    volumes:
      - ./customer/${CUSTOMER}/uploads:/dcmfiles
    ports:
      - "32773:104"
    command: >
      storescp 104 
      -v 
      -aet INNOVATIONDX 
      --output-directory /dicom-data/input
      -fe .dcm 
      +xa
    networks:
      - default

  orthanc:
    image: orthancteam/orthanc:latest
    ports: [8042:8042]
    env_file:
      - .env
    volumes:
      - orthanc-sqlite-storage:/var/lib/orthanc/db
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio-data:/data
    entrypoint: sh
    command: -c 'mkdir -p /data/orthanc && /usr/bin/docker-entrypoint.sh server /data --console-address ":9001"'

  ohif:
    image: ohif/app:latest
    ports:
      - "8080:80"
    volumes:
      - ./ohif.js:/usr/share/nginx/html/app-config.js
    depends_on:
      - orthanc

  nginx:
    image: nginx:latest
    ports:
      - "3080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - orthanc
      - ohif

volumes:
  orthanc-sqlite-storage:
  minio-data:

networks:
  default:
    driver: bridge 