services:
  dicomweb:
    build: .
    ports:
      - "${DICOM_WEB_PORT}:${DICOM_WEB_PORT}"  # OHIF viewer web interface
      - "${DICOM_SERVER_PORT}:${DICOM_SERVER_PORT}"  # DICOM DIMSE port
    command: npx dicomweb-pacs
    environment:
      - AE_TITLE=${DICOM_AE_TITLE}
      - HOSTNAME=dicomweb
      - DICOM_SERVER_PORT=${DICOM_SERVER_PORT}
      - DICOM_SERVER_HOST=${DICOM_SERVER_HOST}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${DICOM_SERVER_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./dicom_data:/app/data  # For persistent storage
    networks:
      intelpixel:
        aliases:
          - dicom
  dicomlistener:
    image: darthunix/dcmtk:latest
    volumes:
      - ./customer/${CUSTOMER}/uploads:/dcmfiles
    ports:
      - "32773:104"
    command: storescp 104 -v -aet INTELPIXEL --output-directory /dcmfiles -fe .dcm +xa
    networks:
      - intelpixel
    depends_on:
      - minio
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - ./customer/${CUSTOMER}:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - intelpixel

networks:
  intelpixel:
    name: intelpixel
