services:
  dicomweb:
    build: .
    ports:
      - "8080:5985"
    command: npm start
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      intelpixel:
        aliases:
          - dicom
  dicomlistener:
    image: darthunix/dcmtk:latest
    volumes:
      - ./customer/${CUSTOMER}/uploads:/dcmfiles
    ports:
      - "32773:104"
    command: storescp 104 -v -aet INTELPIXEL --output-directory /dcmfiles -fe .dcm +xa
    networks:
      - intelpixel
    depends_on:
      - minio
  couchdb:
    image: couchdb:3.3
    expose:
      - "5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    command: >
      sh -c "
        tini -- /docker-entrypoint.sh /opt/couchdb/bin/couchdb &
        sleep 15 &&
        curl -X PUT http://${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-password}@localhost:5984/_users &&
        curl -X PUT http://${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-password}@localhost:5984/_replicator &&
        curl -X PUT http://${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-password}@localhost:5984/_global_changes &&
        wait
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./demo_couchdb_data:/opt/couchdb/data
    networks:
      intelpixel:
        aliases:
          - db
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - ./customer/${CUSTOMER}:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - intelpixel

networks:
  intelpixel:
    name: intelpixel
